spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.104.212.188:3306/test?charactEncoding=utf-8&useSSL=false
    username: root
    password: Mysql5.7!
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
  thymeleaf:
    cache: false
    enabled: true
    mode: HTML5

  redis:
    host: 47.104.212.188
    port: 6379
    database: 1
  profiles:
    active: dev
  mail:
    host: smtp.163.com
    username: eazyfree@163.com
    password: ZZq930210
    port: 25
    default-encoding: UTF-8
    test-connection: false
    from-addr: eazyfree@163.com
server:
  port: 80

