spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.104.212.188:3306/test?charactEncoding=utf-8&useSSL=false
    username: root
    password: Mysql5.7!
  jpa:
    show-sql: true
    generate-ddl: true
